theme: minima
title: Samiikon Blog
author: Sami Ikonen
description: Python, Flask, CouchDB, backend in general
permalink: pretty
twitter_username: samiikon
github_username: samiikon
header_pages:
 - index.md
